### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mkiser** [algorithmiaio/algorithmia-nodejs#6]
No matter what algorithm I try to call from a nodejs app, I get the following TypeError.

**error:**
```
/XXXX/XXXXX/node_modules/algorithmia/lib/algorithmia.js:75
        if (ct.startsWith('application/json')) {
               ^
TypeError: undefined is not a function
    at IncomingMessage.<anonymous> (/XXXX/XXXXX/node_modules/algorithmia/lib/algorithmia.js:75:16)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**call:**

```
var algorithmia = require("algorithmia");
var client = algorithmia('API KEY');

client.algo("algo://demo/Hello/0.1.1")
    .pipe("HAL 9000")
    .then(function(response) {
    console.log(response.get());
    });
```

Have tried rotating API keys, spinning up a fresh node app, and trying a bunch of different algorithms, but no dice.

**Comment by peckjon** [comment]
Take off the .get()

**Comment by mkiser** [comment]
Thx. Still getting the same error, tho.

For what it's worth, the sample call above is from the client docs:
http://developers.algorithmia.com/application-development/client-guides/node/

**Comment by peckjon** [comment]
Sorry, I see it now.  The offending lines are `ct = res.headers['content-type'] || accept; if (ct.startsWith('application/json')) ...`

It looks like neither `res.headers['content-type']` nor `accept` (which is `dheader['Accept'] `) are defined... which is strange, since `dheader['Accept']` was set on line 48.

Is the lib up to date?  Try a `npm update algorithmia` perhaps?

**Comment by mkiser** [comment]
Yep, tried that and nuked the entire app and reinstalled everything fresh and it still happens.

Rolled back two minor updates to 0.3.5 and it works.

**Comment by peckjon** [comment]
Odd, I did the following exactly, in a blank dir, with `index.js` containing only your code snippet above:

```
npm init
npm install --save algorithmia
node index.js
```

output: `Hello HAL 9000`

Any other details that might be helpful... other libs etc?  OSX 10.12.2 ?

**Comment by mkiser** [comment]
eesh. it was an outdated node. updated to v6.9.4 and all is well, again. thx.

**Comment by peckjon** [comment]
👍
